/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliverySend;

import EcoSystem.EcoSystem;
import Enterprise.DeliveryEnterprise;
import Enterprise.Enterprise;
import Network.Network;
import Person.UserAccount;
import WorkRequest.TransportWorkRequest;
import WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caobo
 */
public class DeliverySendWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;
    Network network;
    UserAccount account;

    /**
     * Creates new form DeliverySendWorkAreaJPanel
     */
    public DeliverySendWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.account = account;
        this.enterprise=enterprise;
        this.network = network;
        valueLabel.setText(enterprise.getName());
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnMngSend.setText("Manage Send Request");
        btnMngSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSendActionPerformed(evt);
            }
        });
        add(btnMngSend);
        btnMngSend.setBounds(429, 164, 250, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Delivery Send Role");
        add(jLabel1);
        jLabel1.setBounds(360, 69, 408, 29);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(429, 116, 120, 30);

        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(561, 125, 130, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSendActionPerformed
        // TODO add your handling code here:
        ManageDeliverySendRequestJPanel manageDeliverySendRequestJPanel = new ManageDeliverySendRequestJPanel(userProcessContainer,account, enterprise,network,system);
        userProcessContainer.add("manageDeliverySendRequestJPanel", manageDeliverySendRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngSend;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
