/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliverySend;

import EcoSystem.EcoSystem;
import Enterprise.CharityEnterprise;
import Enterprise.DeliveryEnterprise;
import Enterprise.Enterprise;
import Network.Network;
import Person.UserAccount;
import UserInterface.CharityReceive.ViewGoodsOrderJPanel;
import WorkRequest.SendWorkRequest;
import WorkRequest.TransportWorkRequest;
import WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanfei
 */

public class ManageDeliverySendRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;
    Network network;
    UserAccount account;
    /**
     * Creates new form ManageDeliverySendRequestJPanel
     */
    public ManageDeliverySendRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=business;
        this.account = account;
        this.enterprise=enterprise;
        this.network = network;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
        dtm.setRowCount(0);
        
        if(enterprise instanceof DeliveryEnterprise){
            for(WorkRequest workRequest:((DeliveryEnterprise)enterprise).getWorkQueue().getWorkRequestList()){
                if(workRequest instanceof TransportWorkRequest){
                    TransportWorkRequest request = (TransportWorkRequest)workRequest;
                    if(request.getStatus() == 1 && request.getTransportType() == 2){
                    
                        Object[] row = new Object[8];
                        row[0] = request;
                        row[1] = request.getSender().getUsername();
                        row[2] = request.getStatus();
                        row[3] = request.getRequestDate();
                        row[4] = request.getTransportType();
                        row[5] = request.getDistance();
                        row[6] = request.getPrice();
                        row[7] = request.getTime();
                        dtm.addRow(row);                
                    }
                }
            }
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 550, 59, 34);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Goods Order ", "Sender", "Status", "Request Date", "TransportTye", "Distance", "Price", "Estimated Delivery"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1);
        jScrollPane1.setBounds(194, 110, 870, 415);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(980, 80, 75, 34);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        enterpriseLabel1.setText("Delivery Request");
        add(enterpriseLabel1);
        enterpriseLabel1.setBounds(170, 30, 247, 30);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend);
        btnSend.setBounds(1000, 540, 59, 34);

        jLabel1.setText("Delivery this request");
        add(jLabel1);
        jLabel1.setBounds(840, 550, 155, 18);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
        TransportWorkRequest workRequest = (TransportWorkRequest) tblOrder.getValueAt(selectedRow, 0);
        workRequest.setTransportType(3); // sent
        workRequest.setStatus(3);
        workRequest.getReceiver().getWorkQueue().getWorkRequestList().add(workRequest);
        JOptionPane.showMessageDialog(null, "Sent!");
        populateTable();
        }

//        TransportWorkRequest request = new TransportWorkRequest();
//        request.setFromEnterprise(enterprise);
//        request.setToEnterprise(toEnterprise);
//        request.setReceiver(userAccount);
//        request.setRequestDate(new Date());
        
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
