/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Main;

import EcoSystem.EcoSystem;
import EcoSystem.DB4OUtil;
import Enterprise.Enterprise;
import Network.Network;
import Organization.Organization;
import Person.UserAccount;
import Role.CitizenRole;
import Role.Role;
import UserInterface.SystemAdmin.ManageNetworkJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author qiaoz
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitJPanel = new javax.swing.JSplitPane();
        LeftJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        ManageBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        RightJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(800, 600));

        SplitJPanel.setDividerLocation(150);
        SplitJPanel.setAutoscrolls(true);

        LeftJPanel.setPreferredSize(new java.awt.Dimension(150, 600));
        LeftJPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Login");
        LeftJPanel.add(jLabel1);
        jLabel1.setBounds(10, 20, 112, 33);
        LeftJPanel.add(userNameText);
        userNameText.setBounds(6, 79, 120, 30);

        jLabel2.setText("User Name:");
        LeftJPanel.add(jLabel2);
        jLabel2.setBounds(6, 51, 100, 20);

        jLabel3.setText("Password:");
        LeftJPanel.add(jLabel3);
        jLabel3.setBounds(6, 138, 70, 18);

        RegisterBtn.setText("Citizen Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        LeftJPanel.add(RegisterBtn);
        RegisterBtn.setBounds(0, 560, 150, 34);

        ManageBtn.setText("Manage Account");
        ManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBtnActionPerformed(evt);
            }
        });
        LeftJPanel.add(ManageBtn);
        ManageBtn.setBounds(0, 510, 150, 34);

        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        LeftJPanel.add(loginBtn);
        loginBtn.setBounds(0, 230, 140, 34);

        logoutBtn.setText("logout");
        logoutBtn.setEnabled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        LeftJPanel.add(logoutBtn);
        logoutBtn.setBounds(0, 280, 140, 34);
        LeftJPanel.add(passwordText);
        passwordText.setBounds(6, 168, 120, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Main/Screen Shot 2017-12-10 at 9.54.47 PM.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        LeftJPanel.add(jLabel6);
        jLabel6.setBounds(0, 0, 150, 800);

        SplitJPanel.setLeftComponent(LeftJPanel);

        RightJPanel.setPreferredSize(new java.awt.Dimension(700, 600));
        RightJPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 600));
        RightJPanel.add(jLabel4, "card2");

        SplitJPanel.setRightComponent(RightJPanel);

        getContentPane().add(SplitJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameText.getText();
        String password = String.valueOf(passwordText.getPassword());
        if(userName.equals("")){
            JOptionPane.showMessageDialog(null, "Please input username!");
            return;
        }
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Username/Password wrong!");
            userNameText.setText("");
            passwordText.setText("");
            return;
        }else{
            Enterprise inEnterprise = userAccount.getEnterprise();
            Organization inOrganization = userAccount.getOrganization();
            Network inNetwork = userAccount.getNetwork();
            CardLayout layout = (CardLayout) RightJPanel.getLayout();
            RightJPanel.add("workArea", userAccount.getRole().createWorkArea(RightJPanel, userAccount, inOrganization, inEnterprise, inNetwork, system));
            layout.next(RightJPanel);
            loginBtn.setEnabled(false);
            logoutBtn.setEnabled(true);
            userNameText.setEnabled(false);
            passwordText.setEnabled(false);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        logoutBtn.setEnabled(false);
        userNameText.setEnabled(true);
        passwordText.setEnabled(true);
        loginBtn.setEnabled(true);

        userNameText.setText("");
        passwordText.setText("");

        RightJPanel.removeAll();
        JPanel blankJP = new JPanel();
        RightJPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) RightJPanel.getLayout();
        crdLyt.next(RightJPanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        RegisterJPanel manageNetworkJPanel = new RegisterJPanel(RightJPanel, system);
        RightJPanel.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) RightJPanel.getLayout();
        layout.next(RightJPanel);
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void ManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameText.getText();
        String password = String.valueOf(passwordText.getPassword());
        if(userName.equals("")){
            JOptionPane.showMessageDialog(null, "Please input username!");
            return;
        }
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Username/Password wrong!");
            userNameText.setText("");
            passwordText.setText("");
            return;
        }else if(!userAccount.getRole().toString().equals("Role.CitizenRole")){
            JOptionPane.showMessageDialog(null, "Not a Citizen Account!");
            userNameText.setText("");
            passwordText.setText("");
            return;
        }else{
            ManageAccountJPanel manageNetworkJPanel = new ManageAccountJPanel(RightJPanel, userAccount, system);
            RightJPanel.add("manageNetworkJPanel", manageNetworkJPanel);
            CardLayout layout = (CardLayout) RightJPanel.getLayout();
            layout.next(RightJPanel);
        }

    }//GEN-LAST:event_ManageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftJPanel;
    private javax.swing.JButton ManageBtn;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JPanel RightJPanel;
    private javax.swing.JSplitPane SplitJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
