/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Main;

import EcoSystem.EcoSystem;
import Enterprise.CitizenEnterprise;
import Enterprise.Enterprise;
import Network.Network;
import Organization.Organization;
import Person.Person;
import Person.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author qiaoz
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    public ManageAccountJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        populatenetwork();
        GenderComboBox.removeAllItems();
        GenderComboBox.addItem("Male");
        GenderComboBox.addItem("Female");
        GenderComboBox.addItem("Hidden");
        networkcombo.setSelectedItem(account.getNetwork());
        enterprisecombo.setSelectedItem(account.getEnterprise());
        organizationcombo.setSelectedItem(account.getOrganization());
        int gender = account.getPerson().getGender();
        if(gender == 1)
            GenderComboBox.setSelectedItem("Male");
        else if(gender == -1)
            GenderComboBox.setSelectedItem("Female");
        else
            GenderComboBox.setSelectedItem("Hidden");
        nameJTextField.setText(account.getPerson().getName());
        IncomeTxt.setText(String.valueOf(account.getPerson().getIncome()));
        FoodCostTxt.setText(String.valueOf(account.getPerson().getFoodSpend()));
        nameJTextField1.setText(account.getUsername());
        passwordJTextField.setText(account.getPassword());
    }
   public void populatenetwork(){
        networkcombo.removeAllItems();
        for(Network net: system.getNetworkList()){
            networkcombo.addItem(net);
        }
    }        

    public void populateenterprise(){
        Network network = (Network)networkcombo.getSelectedItem();
        enterprisecombo.removeAllItems();
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof CitizenEnterprise)
                enterprisecombo.addItem(ent);
        }
    }     
    
    public void populateorganization(){
        Enterprise enterprise = (Enterprise)enterprisecombo.getSelectedItem();
        organizationcombo.removeAllItems();
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            organizationcombo.addItem(org);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderComboBox = new javax.swing.JComboBox<>();
        nameJTextField = new javax.swing.JTextField();
        nameJTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        FoodCostTxt = new javax.swing.JFormattedTextField();
        IncomeTxt = new javax.swing.JFormattedTextField();
        networkcombo = new javax.swing.JComboBox();
        enterprisecombo = new javax.swing.JComboBox();
        organizationcombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(null);

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(GenderComboBox);
        GenderComboBox.setBounds(458, 309, 183, 27);
        add(nameJTextField);
        nameJTextField.setBounds(458, 252, 183, 26);
        add(nameJTextField1);
        nameJTextField1.setBounds(458, 487, 183, 26);

        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(172, 257, 36, 16);
        add(passwordJTextField);
        passwordJTextField.setBounds(458, 548, 183, 26);

        jLabel1.setText("Network:");
        add(jLabel1);
        jLabel1.setBounds(172, 87, 57, 16);

        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(172, 313, 44, 16);

        jLabel4.setText("User Name");
        add(jLabel4);
        jLabel4.setBounds(172, 492, 68, 16);

        jLabel2.setText("Enterprise:");
        add(jLabel2);
        jLabel2.setBounds(172, 141, 67, 16);

        jLabel7.setText("Annual Income");
        add(jLabel7);
        jLabel7.setBounds(172, 372, 94, 16);

        jLabel9.setText("Password");
        add(jLabel9);
        jLabel9.setBounds(172, 553, 59, 16);

        jLabel3.setText("Organization:");
        add(jLabel3);
        jLabel3.setBounds(172, 202, 85, 16);

        jLabel8.setText("Average Food Cost");
        add(jLabel8);
        jLabel8.setBounds(172, 430, 118, 16);

        addJButton.setText("Create");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(641, 602, 84, 29);
        add(FoodCostTxt);
        FoodCostTxt.setBounds(458, 425, 183, 26);
        add(IncomeTxt);
        IncomeTxt.setBounds(458, 367, 183, 26);

        networkcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkcomboActionPerformed(evt);
            }
        });
        add(networkcombo);
        networkcombo.setBounds(458, 83, 183, 27);

        enterprisecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterprisecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisecomboActionPerformed(evt);
            }
        });
        add(enterprisecombo);
        enterprisecombo.setBounds(458, 137, 183, 27);

        organizationcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organizationcombo);
        organizationcombo.setBounds(458, 191, 183, 27);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(91, 602, 75, 29);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(0, 0, 1210, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        Network network = (Network)networkcombo.getSelectedItem();
        Enterprise enterprise = (Enterprise)enterprisecombo.getSelectedItem();
        Organization organization = (Organization) organizationcombo.getSelectedItem();
        String gender = (String)GenderComboBox.getSelectedItem();
        int g = 0;
        if(gender.equals("Male")){
            g = 1;
        }else if(gender.equals("Female")){
            g = -1;
        }else{
            g = 0;
        }
        String name = nameJTextField.getText();
        String income = IncomeTxt.getText();
        String food = FoodCostTxt.getText();
        String username = nameJTextField1.getText();
        String password = String.valueOf(passwordJTextField.getPassword());
        if(name.equals("")||income.equals("")||food.equals("")|username.equals("")||password.equals("")){
            JOptionPane.showMessageDialog(null, "incomplete information");
        }else{
            Person person = account.getPerson();
            person.setGender(g);
            person.setFoodSpend(Double.parseDouble(food));
            person.setIncome(Double.parseDouble(income));
            person.setEngelsCoefficient(person.getFoodSpend()/person.getIncome());

            UserAccount ua = account;
            ua.setEnterprise(enterprise);
            ua.setOrganization(organization);
            ua.setNetwork(network);
            system.getUserAccountDirectory().getUserAccountList().add(ua);
            JOptionPane.showMessageDialog(null, "Updated!");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void networkcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkcomboActionPerformed
        // TODO add your handling code here:
        if(networkcombo.getSelectedItem() != null)
        populateenterprise();
    }//GEN-LAST:event_networkcomboActionPerformed

    private void enterprisecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisecomboActionPerformed
        // TODO add your handling code here:
        if(enterprisecombo.getSelectedItem() != null)
        populateorganization();
    }//GEN-LAST:event_enterprisecomboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            WhiteJPanel manageNetworkJPanel = new WhiteJPanel();
            userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FoodCostTxt;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JFormattedTextField IncomeTxt;
    private javax.swing.JButton addJButton;
    private javax.swing.JComboBox enterprisecombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JComboBox networkcombo;
    private javax.swing.JComboBox organizationcombo;
    private javax.swing.JPasswordField passwordJTextField;
    // End of variables declaration//GEN-END:variables
}
