/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityReceive;

import EcoSystem.EcoSystem;
import Person.Goods;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author caobo
 */
public class EditGoodsOrderJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    Goods goods;

    /**
     * Creates new form EditGoodsOrderJPanel
     */
    public EditGoodsOrderJPanel(JPanel userProcessContainer, EcoSystem system,Goods goods) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.goods = goods;
        
        populateText();    
    }
    
    public void populateText(){
        textCondition.setText(String.valueOf(goods.getCondition()));
        textName.setText(goods.getName());
        textNum.setText(String.valueOf(goods.getNum()));
        textPrice.setText(String.valueOf(goods.getEstimatedPrice()));
        textSize.setText(String.valueOf(goods.getSize()));
        textWeight.setText(String.valueOf(goods.getWeight()));
        textX.setText(String.valueOf(goods.getX()));
        textY.setText(String.valueOf(goods.getY()));
        textZ.setText(String.valueOf(goods.getZ()));
        
        textSize.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textCondition = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textSize = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textWeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textX = new javax.swing.JTextField();
        textY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textZ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setText("Name:");
        add(jLabel2);
        jLabel2.setBounds(250, 79, 86, 16);

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        add(textName);
        textName.setBounds(348, 74, 213, 26);

        jLabel3.setText("Number:");
        add(jLabel3);
        jLabel3.setBounds(250, 123, 86, 16);

        textNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumActionPerformed(evt);
            }
        });
        add(textNum);
        textNum.setBounds(348, 118, 213, 26);

        jLabel4.setText("Condition:");
        add(jLabel4);
        jLabel4.setBounds(250, 167, 86, 16);

        textCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConditionActionPerformed(evt);
            }
        });
        add(textCondition);
        textCondition.setBounds(348, 162, 213, 26);

        jLabel5.setText("Est. Price");
        add(jLabel5);
        jLabel5.setBounds(250, 211, 86, 16);

        textPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPriceActionPerformed(evt);
            }
        });
        add(textPrice);
        textPrice.setBounds(348, 206, 213, 26);

        jLabel6.setText("Size:");
        add(jLabel6);
        jLabel6.setBounds(250, 255, 86, 16);

        textSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSizeActionPerformed(evt);
            }
        });
        add(textSize);
        textSize.setBounds(348, 250, 213, 26);

        jLabel7.setText("Weight:");
        add(jLabel7);
        jLabel7.setBounds(250, 299, 86, 16);

        textWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWeightActionPerformed(evt);
            }
        });
        add(textWeight);
        textWeight.setBounds(348, 294, 213, 26);

        jLabel1.setText("X:");
        add(jLabel1);
        jLabel1.setBounds(250, 338, 12, 16);
        add(textX);
        textX.setBounds(268, 338, 68, 26);
        add(textY);
        textY.setBounds(376, 338, 69, 26);

        jLabel8.setText("Y:");
        add(jLabel8);
        jLabel8.setBounds(358, 338, 12, 16);
        add(textZ);
        textZ.setBounds(494, 338, 67, 26);

        jLabel9.setText("Z:");
        add(jLabel9);
        jLabel9.setBounds(476, 338, 12, 16);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 420, 93, 42);

        btnSave.setText("Save & Update");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(580, 420, 133, 42);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumActionPerformed

    private void textConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConditionActionPerformed

    private void textPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPriceActionPerformed

    private void textSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSizeActionPerformed

    private void textWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWeightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewGoodsOrderJPanel viewGoodsOrderJPanel = (ViewGoodsOrderJPanel) component;
        viewGoodsOrderJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = textName.getText();
        String num = textNum.getText();
        String condition = textCondition.getText();
        String estimatePrice = textPrice.getText();
        String size = textSize.getText();
        String weight = textWeight.getText();
        String x = textX.getText();
        String y = textY.getText();
        String z = textZ.getText();
        
        boolean valid = true;
        if(name.equals("")||num.equals("")||condition.equals("")||estimatePrice.equals("")||size.equals("")||weight.equals("")||x.equals("")||y.equals("")||z.equals("")){
            JOptionPane.showMessageDialog(null, "The value cannot be blank!");
        }else{
            
            
            try{
                if(Double.valueOf(condition)<1||Double.valueOf(condition)>10){
                    JOptionPane.showMessageDialog(null, "The value of condition should between 1 and 10!");
                    valid = false;
                }
                
                if(Integer.valueOf(num)<0||Double.valueOf(size)<0||Double.valueOf(x)<0||Double.valueOf(y)<0||Double.valueOf(z)<0||Double.valueOf(weight)<0){
                    JOptionPane.showMessageDialog(null, "The value should be no less than zero!");
                    valid = false;
                }
            }catch(Exception e){
                valid = false;
                JOptionPane.showMessageDialog(null, "The value format input is wrong!");
            }
            
            if(valid){
                goods.setName(name);
                goods.setNum(Integer.valueOf(num));
                goods.setCondition(Double.valueOf(condition));
                goods.setEstimatedPrice(Double.valueOf(estimatePrice));
                goods.setWeight(Double.valueOf(weight));
                goods.setX(Double.valueOf(x));
                goods.setY(Double.valueOf(y));
                goods.setZ(Double.valueOf(z));
                goods.setSize(goods.getX()*goods.getY()*goods.getZ());
                
                JOptionPane.showMessageDialog(null, "The order information updated successfully!");
                
                textName.setText("");
                textName.setText("");
                textCondition.setText("");
                textPrice.setText("");
                textSize.setText("");
                textWeight.setText("");
                textX.setText("");
                textY.setText("");
                textZ.setText("");
                
                populateText();
                
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textCondition;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNum;
    private javax.swing.JTextField textPrice;
    private javax.swing.JTextField textSize;
    private javax.swing.JTextField textWeight;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textY;
    private javax.swing.JTextField textZ;
    // End of variables declaration//GEN-END:variables
}
