/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityReceive;

import EcoSystem.EcoSystem;
import Enterprise.CharityEnterprise;
import Enterprise.Enterprise;
import Person.GoodsList;
import WorkRequest.SendWorkRequest;
import WorkRequest.WorkQueue;
import WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanfei
 */
public class ManageReceiveComfirmJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageReceiveComfirmJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;
    
    public ManageReceiveComfirmJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise=enterprise;
        valueLabel1.setText(enterprise.getName());
        populateTable();
        btnAdd.setEnabled(false);
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblRequest.getModel();
        dtm.setRowCount(0);
        
        if(enterprise instanceof CharityEnterprise){
            for(WorkRequest workRequest:((CharityEnterprise)enterprise).getWorkQueue().getWorkRequestList()){
                    //getReceiveList().getWorkRequestList()){
                if(workRequest instanceof SendWorkRequest){
                    SendWorkRequest request = (SendWorkRequest)workRequest;
                    if(request.getStatus() != 1 || request.getRequest() != 1){

                    }else{
                        Object[] row = new Object[4];
                        row[0] = request;
                        row[1] = request.getSender().getUsername();
                        row[2] = request.getStatus();
                        row[3] = request.getRequestDate();
                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReject = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        setLayout(null);

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Goods Order ", "Sender", "Status", "Request Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1);
        jScrollPane1.setBounds(218, 114, 676, 335);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("EnterPrise :");
        add(enterpriseLabel1);
        enterpriseLabel1.setBounds(218, 19, 127, 30);

        valueLabel1.setText("<value>");
        add(valueLabel1);
        valueLabel1.setBounds(340, 20, 158, 26);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend);
        btnSend.setBounds(218, 461, 75, 29);

        jLabel1.setText("Send Received Comfirmation");
        add(jLabel1);
        jLabel1.setBounds(345, 466, 184, 16);

        jLabel2.setText("Reject Request");
        add(jLabel2);
        jLabel2.setBounds(343, 576, 92, 16);

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject);
        btnReject.setBounds(218, 571, 75, 29);

        jLabel3.setText("Look into Order Goods Detail");
        add(jLabel3);
        jLabel3.setBounds(345, 501, 184, 16);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(218, 496, 75, 29);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(804, 565, 90, 29);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(803, 79, 91, 29);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(218, 536, 75, 29);

        jLabel4.setText("Add this Order Goods to Charity Inventory ");
        add(jLabel4);
        jLabel4.setBounds(343, 541, 269, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            WorkRequest workRequest = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
            if(workRequest instanceof SendWorkRequest){
                ((SendWorkRequest)workRequest).setRejected(1);
                workRequest.setStatus(2);
                btnSend.setEnabled(false);
                btnReject.setEnabled(false);
                btnAdd.setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Rejected!");
            populateTable();
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            WorkRequest workRequest = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
            GoodsList goodsList = workRequest.getGoodsList();
            
            ViewGoodsOrderJPanel viewGoodsOrderJPanel = new ViewGoodsOrderJPanel(userProcessContainer,system,goodsList);
            userProcessContainer.add("viewGoodsOrderJPanel", viewGoodsOrderJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            WorkRequest workRequest = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
            if(workRequest instanceof SendWorkRequest){
                
                    
                
                    workRequest.setStatus(2);
                    workRequest.setResolveDate(new Date());
                    ((CharityEnterprise)enterprise).getReceiveList().getWorkRequestList().add(workRequest);
                    
                    workRequest.getSender().setDonateIndex(workRequest.getSender().getDonateIndex()+1);
                    
                    btnSend.setEnabled(false);
                    btnReject.setEnabled(false);
                    btnAdd.setEnabled(true);
                    
                    JOptionPane.showMessageDialog(null, "Request sended successfully!");
                 
                
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            WorkRequest workRequest = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
            GoodsList goodsList = workRequest.getGoodsList();
            if(enterprise instanceof CharityEnterprise){
                ((CharityEnterprise)enterprise).getGoodsList().add(goodsList);
            }
            populateTable();
            btnSend.setEnabled(true);
            btnReject.setEnabled(true);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
}
