/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GovAnalyse;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Network.Network;
import Organization.Organization;
import Person.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author caobo
 */
public class GovAnalyseWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer; 
    EcoSystem system;
    UserAccount account;
    Enterprise enterprise;
    Network network;
    Organization organization;
    /**
     * Creates new form GovAnalyseWorkAreaJPanel
     */
    public GovAnalyseWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network = network;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDonationRate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnDeliveryRate = new javax.swing.JButton();
        ViewGoodsBtn = new javax.swing.JButton();
        btnCompliantRate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnDonationRate.setText("View Donation Rate Anaylsis");
        btnDonationRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationRateActionPerformed(evt);
            }
        });
        add(btnDonationRate);
        btnDonationRate.setBounds(457, 164, 250, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Government Anaylze Role");
        add(jLabel1);
        jLabel1.setBounds(358, 56, 492, 29);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(358, 107, 120, 30);

        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(481, 116, 130, 16);

        btnDeliveryRate.setText("View Delivery Efficency Anaylsis");
        btnDeliveryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryRateActionPerformed(evt);
            }
        });
        add(btnDeliveryRate);
        btnDeliveryRate.setBounds(457, 211, 250, 29);

        ViewGoodsBtn.setText("View Goods Preference");
        ViewGoodsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGoodsBtnActionPerformed(evt);
            }
        });
        add(ViewGoodsBtn);
        ViewGoodsBtn.setBounds(460, 310, 250, 29);

        btnCompliantRate.setText("View Compliant Rate Anaylsis");
        btnCompliantRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompliantRateActionPerformed(evt);
            }
        });
        add(btnCompliantRate);
        btnCompliantRate.setBounds(457, 258, 250, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-4, -8, 1210, 810);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonationRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationRateActionPerformed
        // TODO add your handling code here:
        ViewDonationRateJPanel viewDonationRateJPanel = new ViewDonationRateJPanel(userProcessContainer, account, organization, enterprise, network, system);
        userProcessContainer.add("viewDonationRateJPanel", viewDonationRateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonationRateActionPerformed

    private void btnDeliveryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryRateActionPerformed
        // TODO add your handling code here:
        ViewDeliveryRateJPanel viewDeliveryRateJPanel = new ViewDeliveryRateJPanel(userProcessContainer, account, organization, enterprise, network, system);
        userProcessContainer.add("viewDeliveryRateJPanel", viewDeliveryRateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnDeliveryRateActionPerformed

    private void btnCompliantRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompliantRateActionPerformed
        // TODO add your handling code here:
        ViewCompliantRateJPanel viewCompliantRateJPanel = new ViewCompliantRateJPanel(userProcessContainer, account, organization, enterprise, network, system);
        userProcessContainer.add("viewCompliantRateJPanel", viewCompliantRateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCompliantRateActionPerformed

    private void ViewGoodsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGoodsBtnActionPerformed
        // TODO add your handling code here:
        ViewGoodsJPanel viewCompliantRateJPanel = new ViewGoodsJPanel(userProcessContainer, account, organization, enterprise, network, system);
        userProcessContainer.add("viewCompliantRateJPanel", viewCompliantRateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewGoodsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewGoodsBtn;
    private javax.swing.JButton btnCompliantRate;
    private javax.swing.JButton btnDeliveryRate;
    private javax.swing.JButton btnDonationRate;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
