/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Citizen;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Network.Network;
import Person.UserAccount;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author caobo
 */
public class CitizenWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer; 
    EcoSystem system;
    Enterprise enterprise;
    Network network;
    UserAccount account;
    /**
     * Creates new form CitizenWorkAreaJPanel
     */
    public CitizenWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.enterprise = enterprise;
        this.network = network;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDonate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCompliant = new javax.swing.JButton();
        HistoryBtn = new javax.swing.JButton();
        PinnedBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        btnView.setText("View Posted Request from Donee");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(387, 152, 250, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Citizen Role");
        add(jLabel1);
        jLabel1.setBounds(357, 66, 326, 29);

        btnDonate.setText("Donate Item");
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });
        add(btnDonate);
        btnDonate.setBounds(387, 193, 251, 29);

        btnSearch.setText("Search for Avail Good ");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(387, 240, 251, 29);

        btnRequest.setText("Send Request for Item");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest);
        btnRequest.setBounds(387, 287, 250, 29);

        jLabel2.setText("As Donee");
        add(jLabel2);
        jLabel2.setBounds(666, 245, 60, 16);

        jLabel3.setText("As Donee");
        add(jLabel3);
        jLabel3.setBounds(660, 290, 60, 16);

        jLabel4.setText("As Donor");
        add(jLabel4);
        jLabel4.setBounds(666, 157, 59, 16);

        jLabel5.setText("As Donor");
        add(jLabel5);
        jLabel5.setBounds(666, 198, 59, 16);

        btnCompliant.setText("Send Complain");
        btnCompliant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompliantActionPerformed(evt);
            }
        });
        add(btnCompliant);
        btnCompliant.setBounds(387, 334, 251, 29);

        HistoryBtn.setText("View History");
        HistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBtnActionPerformed(evt);
            }
        });
        add(HistoryBtn);
        HistoryBtn.setBounds(390, 380, 250, 29);

        PinnedBtn.setText("Pinned");
        PinnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinnedBtnActionPerformed(evt);
            }
        });
        add(PinnedBtn);
        PinnedBtn.setBounds(780, 30, 86, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewRequestJPanel viewRequestJPanel = new ViewRequestJPanel(userProcessContainer, account, enterprise, network,system);
        userProcessContainer.add("viewRequestJPanel", viewRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SearchGoodsJPanel searchgoodsJPanel = new SearchGoodsJPanel(userProcessContainer,account, enterprise, network,system);
        userProcessContainer.add("searchgoodsJPanel", searchgoodsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        SendRequestJPanel sendRequestJPanel = new SendRequestJPanel(userProcessContainer, account, enterprise, network,system);
        userProcessContainer.add("sendRequestJPanel", sendRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed
        // TODO add your handling code here:
        DonateJPanel donateJPanel = new DonateJPanel(userProcessContainer,account, enterprise, network,system);
        userProcessContainer.add("donateJPanel", donateJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonateActionPerformed

    private void btnCompliantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompliantActionPerformed
        // TODO add your handling code here:
        SendComplaintJPanel sendComplaintJPanel = new SendComplaintJPanel(userProcessContainer,account, enterprise, network, system);
        userProcessContainer.add("sendComplaintJPanel", sendComplaintJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCompliantActionPerformed

    private void HistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBtnActionPerformed
        // TODO add your handling code here:
        HistoryJPanel sendComplaintJPanel = new HistoryJPanel(userProcessContainer,account, enterprise, network, system);
        userProcessContainer.add("historyJPanel", sendComplaintJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_HistoryBtnActionPerformed

    private void PinnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinnedBtnActionPerformed
        // TODO add your handling code here:
        JPanel jp = new JPanel();
        JFrame jf = new JFrame();
        jf.setVisible(true);
        jf.setSize(new Dimension(800,600));
        JPanel tmp = new PinRequestJPanel(account);
        
        JButton close = new JButton("close");
        tmp.add(close);
        
        jf.setContentPane(tmp);
    }//GEN-LAST:event_PinnedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistoryBtn;
    private javax.swing.JButton PinnedBtn;
    private javax.swing.JButton btnCompliant;
    private javax.swing.JButton btnDonate;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
