/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Citizen;

import EcoSystem.EcoSystem;
import Enterprise.CharityEnterprise;
import Enterprise.Enterprise;
import Network.Network;
import Person.Goods;
import Person.GoodsList;
import Person.UserAccount;
import WorkRequest.SendWorkRequest;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanfei
 */
public class DonateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonateJPanel
     */
    JPanel userProcessContainer; 
    EcoSystem system;
    GoodsList goodsList;
    Network network;
    Enterprise enterprise;
    UserAccount account;
    Goods goods;
    public DonateJPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network = network;
        this.enterprise = enterprise;
        this.account = account;
        goodsList = new GoodsList();
        populateComboBox();
        btnAdd.setEnabled(false);
    }
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblDonationOrder.getModel();
        
        model.setRowCount(0);
        for(Goods goods: goodsList.getGoodsList()){
            Object[] row = new Object[2];
            row[0] = goods;
            row[1] = goods.getNum();
            model.addRow(row);
        }
    }
    
    public void populateComboBox(){
        CharityComboBox.removeAllItems();
        for(Enterprise ent:network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof CharityEnterprise){
                CharityComboBox.addItem(ent);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonationOrder = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        SendDonationBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtQuantity = new javax.swing.JFormattedTextField();
        CharityComboBox = new javax.swing.JComboBox();
        DetailBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        PinnedBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setText("Donate Items");
        add(jLabel1);
        jLabel1.setBounds(310, 40, 134, 31);

        jLabel2.setText("Item Name");
        add(jLabel2);
        jLabel2.setBounds(317, 99, 68, 16);
        add(txtItemName);
        txtItemName.setBounds(455, 94, 192, 26);

        jLabel3.setText("Quantity");
        add(jLabel3);
        jLabel3.setBounds(317, 131, 68, 16);

        tblDonationOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblDonationOrder);

        add(jScrollPane1);
        jScrollPane1.setBounds(317, 197, 461, 178);

        btnAdd.setText("Add to Order");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(670, 130, 100, 20);

        SendDonationBtn.setText("Send Donation Request");
        SendDonationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendDonationBtnActionPerformed(evt);
            }
        });
        add(SendDonationBtn);
        SendDonationBtn.setBounds(590, 410, 190, 29);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(60, 410, 75, 29);

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        add(txtQuantity);
        txtQuantity.setBounds(455, 126, 192, 26);

        CharityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(CharityComboBox);
        CharityComboBox.setBounds(320, 410, 180, 27);

        DetailBtn.setText("Item Detail");
        DetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailBtnActionPerformed(evt);
            }
        });
        add(DetailBtn);
        DetailBtn.setBounds(670, 100, 100, 20);

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        add(DeleteBtn);
        DeleteBtn.setBounds(510, 410, 84, 29);

        PinnedBtn.setText("Pinned");
        PinnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinnedBtnActionPerformed(evt);
            }
        });
        add(PinnedBtn);
        PinnedBtn.setBounds(670, 40, 100, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, -10, 1200, 820);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtItemName.getText();
        String num = txtQuantity.getText();
        if(name.equals("")||num.equals("")){
            JOptionPane.showMessageDialog(null, "The input cannot be blank!");
        }else{
                        
            boolean numInvalid = false;
            int quantity = -1;
            try{
                quantity = Integer.parseInt(num);
            }catch (Exception e){
                numInvalid = true;
                return;
            }
            
            if(quantity <1||numInvalid){
                JOptionPane.showMessageDialog(null,"wrong number!");
            }else{
                goods.setName(name);
                goods.setNum(quantity);
                goodsList.getGoodsList().add(goods);
                goods = null;
                txtItemName.setText("");
                txtQuantity.setText("");
                populateTable();
                btnAdd.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void SendDonationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendDonationBtnActionPerformed
        // TODO add your handling code here:
        if(goodsList.getGoodsList().size()==0){
            JOptionPane.showMessageDialog(null, "no goods");
        }else{
            Enterprise ent = (Enterprise)CharityComboBox.getSelectedItem();
            SendWorkRequest workRequest = new SendWorkRequest();
            workRequest.setFromEnterprise(enterprise);
            workRequest.setToEnterprise(ent);
            workRequest.setRequest(1);
            workRequest.setRequestDate(new Date());
            workRequest.setSender(account);
            workRequest.setStatus(1);
            workRequest.setGoodsList(goodsList);
            workRequest.setFromOrganization(account.getOrganization());
            ent.getWorkQueue().getWorkRequestList().add(workRequest);
            account.getWorkQueue().getWorkRequestList().add(workRequest);

            goodsList = new GoodsList();
            JOptionPane.showMessageDialog(null, "Request Sent!");
            populateTable();
        }
    }//GEN-LAST:event_SendDonationBtnActionPerformed

    private void DetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailBtnActionPerformed
        // TODO add your handling code here:
        
        if(goods == null)
            goods = new Goods();
        ItemDetailJPanel viewRequestJPanel = new ItemDetailJPanel(userProcessContainer, goods);
        userProcessContainer.add("viewRequestJPanel", viewRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_DetailBtnActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int selected = tblDonationOrder.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(null, "Please select a row to delete");
        }else{
            Goods gd = (Goods)tblDonationOrder.getValueAt(selected, 0);
            goodsList.getGoodsList().remove(gd);
            populateTable();
            JOptionPane.showMessageDialog(null, "Remove Successfully");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void PinnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinnedBtnActionPerformed
        // TODO add your handling code here:
        JPanel jp = new JPanel();
        JFrame jf = new JFrame();
        jf.setVisible(true);
        jf.setSize(new Dimension(800,600));
        JPanel tmp = new PinRequestJPanel(account);

        JButton close = new JButton("close");
        tmp.add(close);

        jf.setContentPane(tmp);
    }//GEN-LAST:event_PinnedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CharityComboBox;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DetailBtn;
    private javax.swing.JButton PinnedBtn;
    private javax.swing.JButton SendDonationBtn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDonationOrder;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JFormattedTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
