/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Citizen;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Network.Network;
import Person.Goods;
import Person.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author qiaoz
 */
public class ItemDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemDetailJPanel
     */
    JPanel userProcessContainer;
    Goods goods;
    public ItemDetailJPanel(JPanel userProcessContainer,Goods goods) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.goods = goods;
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("10");
        jComboBox1.addItem("9");
        jComboBox1.addItem("8");
        jComboBox1.addItem("7");
        jComboBox1.addItem("6");
        jComboBox1.addItem("5");
        jComboBox1.addItem("4");
        jComboBox1.addItem("3");
        jComboBox1.addItem("2");
        jComboBox1.addItem("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        priceTxt = new javax.swing.JFormattedTextField();
        xTxt = new javax.swing.JFormattedTextField();
        yTxt = new javax.swing.JFormattedTextField();
        zTxt = new javax.swing.JFormattedTextField();
        weightTxt = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PictureBtn = new javax.swing.JButton();
        PicLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(507, 87, 150, 27);

        jLabel1.setText("Condition:");
        add(jLabel1);
        jLabel1.setBounds(386, 91, 66, 16);

        jLabel2.setText("Estimated Price:");
        add(jLabel2);
        jLabel2.setBounds(386, 156, 100, 16);

        jLabel3.setText("Length:");
        add(jLabel3);
        jLabel3.setBounds(386, 215, 47, 16);

        jLabel4.setText("Width");
        add(jLabel4);
        jLabel4.setBounds(386, 270, 36, 16);

        jLabel5.setText("Height");
        add(jLabel5);
        jLabel5.setBounds(386, 326, 42, 16);

        jLabel6.setText("Weight:");
        add(jLabel6);
        jLabel6.setBounds(386, 387, 47, 16);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn);
        SaveBtn.setBounds(630, 470, 75, 29);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn);
        BackBtn.setBounds(90, 470, 75, 30);
        add(priceTxt);
        priceTxt.setBounds(507, 156, 145, 26);
        add(xTxt);
        xTxt.setBounds(507, 210, 145, 26);
        add(yTxt);
        yTxt.setBounds(507, 265, 145, 26);
        add(zTxt);
        zTxt.setBounds(507, 321, 145, 26);
        add(weightTxt);
        weightTxt.setBounds(507, 382, 145, 26);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Item Detail");
        add(jLabel12);
        jLabel12.setBounds(210, 30, 290, 22);

        jLabel11.setText("kg");
        add(jLabel11);
        jLabel11.setBounds(670, 390, 30, 16);

        jLabel10.setText("cm");
        add(jLabel10);
        jLabel10.setBounds(670, 330, 19, 16);

        jLabel8.setText("cm");
        add(jLabel8);
        jLabel8.setBounds(670, 210, 60, 20);

        jLabel9.setText("cm");
        add(jLabel9);
        jLabel9.setBounds(670, 210, 60, 140);

        PictureBtn.setText("Select Picture");
        PictureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PictureBtnActionPerformed(evt);
            }
        });
        add(PictureBtn);
        PictureBtn.setBounds(500, 470, 128, 29);
        add(PicLabel);
        PicLabel.setBounds(230, 440, 250, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean check(){
        String price = priceTxt.getText();
        String x = xTxt.getText();
        String y = yTxt.getText();
        String z = zTxt.getText();
        String weight = weightTxt.getText();
        if(price.equals("")||x.equals("")|| y.equals("") || z.equals("")||  weight.equals("")){
            JOptionPane.showMessageDialog(null, "error input");
            return false;
        }else
            return true;
    }
    
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        if(check()){
            double condition = Double.parseDouble((String)jComboBox1.getSelectedItem());
            double price = Double.parseDouble(priceTxt.getText());
            double x = Double.parseDouble(xTxt.getText());
            double y = Double.parseDouble(yTxt.getText());
            double z = Double.parseDouble(zTxt.getText());
            double weight = Double.parseDouble(weightTxt.getText());
           
            
            goods.setCondition(condition);
            goods.setEstimatedPrice(price);
            goods.setX(x);
            goods.setY(y);
            goods.setZ(z);
            goods.setSize(x*y*z);
            goods.setWeight(weight);
            goods.setPicLink(PicLinkTmp);
            JOptionPane.showMessageDialog(null, "success!");
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    String PicLinkTmp = "empty";
    private void PictureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PictureBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setCurrentDirectory(new File("."));
        int result = chooser.showDialog(new JLabel(), "Select a Picture");
        if(result == JFileChooser.APPROVE_OPTION){
            //get image path
            String name = chooser.getSelectedFile().getPath();
            // Image image = new ImageIcon(name).getImage();
            ImageIcon icon = new ImageIcon(name);

            int imgWidth=icon.getIconWidth();
            int imgHeight=icon.getIconHeight();
            int conWidth=PicLabel.getWidth();
            int conHeight=PicLabel.getHeight();

            int reImgWidth;
            int reImgHeight;
            if(imgWidth/imgHeight>=conWidth/conHeight){
                if(imgWidth>conWidth){
                    reImgWidth=conWidth;
                    reImgHeight=imgHeight*reImgWidth/imgWidth;
                }else{
                    reImgWidth=imgWidth;
                    reImgHeight=imgHeight;
                }
            }else{
                if(imgWidth>conWidth){
                    reImgHeight=conHeight;
                    reImgWidth=imgWidth*reImgHeight/imgHeight;
                }else{
                    reImgWidth=imgWidth;
                    reImgHeight=imgHeight;
                }
            }

            icon=new ImageIcon(icon.getImage().getScaledInstance(reImgWidth, reImgHeight, Image.SCALE_DEFAULT));
            PicLabel.setIcon(icon);
            //save pic path
            PicLinkTmp = name;
        }
    }//GEN-LAST:event_PictureBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel PicLabel;
    private javax.swing.JButton PictureBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField priceTxt;
    private javax.swing.JFormattedTextField weightTxt;
    private javax.swing.JFormattedTextField xTxt;
    private javax.swing.JFormattedTextField yTxt;
    private javax.swing.JFormattedTextField zTxt;
    // End of variables declaration//GEN-END:variables
}
