/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Citizen;

import EcoSystem.EcoSystem;
import Enterprise.CitizenEnterprise;
import Enterprise.Enterprise;
import Enterprise.GovEnterprise;
import Network.Network;
import Person.UserAccount;
import WorkRequest.ComplainWorkRequest;
import WorkRequest.WorkRequest;
import com.db4o.ext.Status;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanfei
 */
public class SendComplaintJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer; 
    EcoSystem system;
    Network network;
    Enterprise enterprise;
    UserAccount account;
    /**
     * Creates new form CitizenWorkAreaJPanel
     */
    public SendComplaintJPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network = network;
        this.enterprise = enterprise;
        this.account = account;
        populateComboBox();
        populate();
        ReplyArea.setEditable(false);
    }
    public void populateComboBox(){
        EnterpriseComboBox.removeAllItems();
        for(Enterprise ent:network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof CitizenEnterprise){
                
            }else{
                EnterpriseComboBox.addItem(ent);
            }
        }
    }
    
    public void populate(){
        DefaultTableModel model = (DefaultTableModel)HistoryTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            if(request instanceof ComplainWorkRequest){
                Object[] row = new Object[2];
                row[0] = request;
                row[1] = request.getStatus();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendMessage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        EnterpriseComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        ViewBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReplyArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnSendMessage.setText("Send Message");
        btnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageActionPerformed(evt);
            }
        });
        add(btnSendMessage);
        btnSendMessage.setBounds(272, 120, 120, 29);

        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(200, 90, 54, 16);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        enterpriseLabel.setText("Send Complain And View Reply");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(200, 30, 290, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(400, 80, 457, 100);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(60, 540, 75, 29);

        EnterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(EnterpriseComboBox);
        EnterpriseComboBox.setBounds(270, 80, 120, 27);

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Reply"
            }
        ));
        jScrollPane2.setViewportView(HistoryTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(270, 240, 590, 120);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        add(ViewBtn);
        ViewBtn.setBounds(790, 370, 75, 29);

        ReplyArea.setColumns(20);
        ReplyArea.setRows(5);
        jScrollPane3.setViewportView(ReplyArea);

        add(jScrollPane3);
        jScrollPane3.setBounds(270, 450, 590, 110);

        jLabel3.setText("HIstory");
        add(jLabel3);
        jLabel3.setBounds(200, 240, 46, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, -10, 1200, 820);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageActionPerformed
        String message = jTextArea1.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null,"please write");
        }else{
            Enterprise ent = null;
            for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof GovEnterprise)
                    ent = e;
            }
            
            if(ent == null){
                JOptionPane.showMessageDialog(null, "No Gov Enterprise!");
            }else{
                Enterprise enter = (Enterprise)EnterpriseComboBox.getSelectedItem();
                ComplainWorkRequest workRequest = new ComplainWorkRequest();
                workRequest.setMessage(message);
                workRequest.setFromEnterprise(enterprise);
                workRequest.setRequestDate(new Date());
                workRequest.setSender(account);
                workRequest.setToEnterprise(ent);
                workRequest.setStatus(1);
                workRequest.setComplainEnterprise(enter);
                workRequest.setFromOrganization(account.getOrganization());
                
                for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
                    if(ent instanceof GovEnterprise){
                        ent.getWorkQueue().getWorkRequestList().add(workRequest);
                        break;
                    }
                }
                account.getWorkQueue().getWorkRequestList().add(workRequest);
                jTextArea1.setText("");
                JOptionPane.showMessageDialog(null, "Complain Sent!");
                populate();
            }
        }

 

    }//GEN-LAST:event_btnSendMessageActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        int selected = HistoryTable.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(null, "please select a row");
        }else{
            WorkRequest request = (WorkRequest)HistoryTable.getValueAt(selected, 0);
            if(request.getStatus() != 2){
                JOptionPane.showMessageDialog(null,"Not finished, no reply");
            }else{
                ReplyArea.setText(((ComplainWorkRequest)request).getResponse());
                ReplyArea.setEditable(false);
            }
        }
    }//GEN-LAST:event_ViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EnterpriseComboBox;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JTextArea ReplyArea;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
