/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Citizen;

import EcoSystem.EcoSystem;
import Enterprise.CharityEnterprise;
import Enterprise.Enterprise;
import Network.Network;
import Person.UserAccount;
import UserInterface.CharityReceive.ViewGoodsOrderJPanel;
import WorkRequest.SendWorkRequest;
import WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanfei
 */
public class ViewRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRequestJPanel
     */
    JPanel userProcessContainer; 
    EcoSystem system;
    Network network;
    Enterprise enterprise;
    UserAccount account;
    public ViewRequestJPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Network network,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network = network;
        this.enterprise = enterprise;
        this.account = account;
        display();
    }
    
    public void display(){
        DefaultTableModel model = (DefaultTableModel) btnRequest.getModel();
        
        model.setRowCount(0);
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof CharityEnterprise){
                for(WorkRequest request: ent.getWorkQueue().getWorkRequestList()){
                    if(request instanceof SendWorkRequest){
                        if(((SendWorkRequest) request).getRequest() == 2){
                            Object[] row = new Object[4];
                            row[0] = request;
                            row[1] = request.getSender();
                            row[2] = request.getStatus();
                            row[3] = request.getRequestDate();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnRequest = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        PinBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PinnedBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(693, 428, 75, 29);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(60, 430, 75, 29);

        btnRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Goods Order ", "Sender", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(btnRequest);

        add(jScrollPane1);
        jScrollPane1.setBounds(244, 123, 524, 293);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(680, 80, 91, 29);

        PinBtn.setText("Pin");
        PinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinBtnActionPerformed(evt);
            }
        });
        add(PinBtn);
        PinBtn.setBounds(420, 430, 75, 29);

        jLabel3.setText("Look into Request Detail");
        add(jLabel3);
        jLabel3.setBounds(244, 433, 155, 16);

        jLabel1.setText("View What donee needs");
        add(jLabel1);
        jLabel1.setBounds(244, 468, 147, 16);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setText("View Current Request From Donee");
        add(jLabel2);
        jLabel2.setBounds(244, 31, 321, 22);

        PinnedBtn.setText("Pinned");
        PinnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinnedBtnActionPerformed(evt);
            }
        });
        add(PinnedBtn);
        PinnedBtn.setBounds(680, 40, 90, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(10, -10, 1200, 820);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = btnRequest.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "select a row");
        }else{
            WorkRequest request = (WorkRequest)btnRequest.getValueAt(row, 0);
            ViewGoodsOrderJPanel viewGoodsOrderJPanel = new ViewGoodsOrderJPanel(userProcessContainer,request,system);
            userProcessContainer.add("viewGoodsOrderJPanel", viewGoodsOrderJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void PinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinBtnActionPerformed
        // TODO add your handling code here:
        int selected = btnRequest.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(null, "please select a row");
        }else{
            WorkRequest request = (SendWorkRequest)btnRequest.getValueAt(selected, 0);
            if(account.getPinWorkQueue().getWorkRequestList().contains(request)){
                JOptionPane.showMessageDialog(null, "already pinned");
                return;
            }
            account.getPinWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Pin success!");
        }
    }//GEN-LAST:event_PinBtnActionPerformed

    private void PinnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinnedBtnActionPerformed
        // TODO add your handling code here:
        JPanel jp = new JPanel();
        JFrame jf = new JFrame();
        jf.setVisible(true);
        jf.setSize(new Dimension(800,600));
        JPanel tmp = new PinRequestJPanel(account);

        JButton close = new JButton("close");
        tmp.add(close);

        jf.setContentPane(tmp);
    }//GEN-LAST:event_PinnedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PinBtn;
    private javax.swing.JButton PinnedBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTable btnRequest;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
