/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliveryReceive;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Network.Network;
import Person.UserAccount;
import UserInterface.CharityReceive.ManageReceiveComfirmJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author caobo
 */
public class DeliveryReceiveWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;
    Network network;
    UserAccount account;
    

    /**
     * Creates new form DeliveryReceiveWorkAreaJPanel
     */
    public DeliveryReceiveWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.account = account;
        this.enterprise=enterprise;
        this.network = network;
        valueLabel.setText(enterprise.getName());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngReceive = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnMngReceive.setText("Manage Receive Comfirmation");
        btnMngReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngReceiveActionPerformed(evt);
            }
        });
        add(btnMngReceive);
        btnMngReceive.setBounds(424, 164, 250, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Delivery Receive Role");
        add(jLabel1);
        jLabel1.setBounds(334, 69, 442, 29);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(334, 116, 120, 30);

        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(472, 125, 130, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngReceiveActionPerformed
        // TODO add your handling code here:
        ManageDeliveryReceiveComfirmJPanel manageReceiveDeliveryComfirmJPanel = new ManageDeliveryReceiveComfirmJPanel(userProcessContainer,account, enterprise,network,system);
        userProcessContainer.add("manageReceiveDeliveryComfirmJPanel", manageReceiveDeliveryComfirmJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngReceiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngReceive;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
