/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityManage;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author caobo
 */
public class CharityManageWorkAreaJPanel extends javax.swing.JPanel {
    
    
    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;

    /**
     * Creates new form CharityManageWorkAreaJPanel
     */
    public CharityManageWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=business;
        this.enterprise=enterprise;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngInv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnMngInv.setText("Manage Charity Inventory");
        btnMngInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInvActionPerformed(evt);
            }
        });
        add(btnMngInv);
        btnMngInv.setBounds(273, 164, 250, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Charity Manage Role");
        add(jLabel1);
        jLabel1.setBounds(245, 69, 430, 29);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(281, 116, 120, 30);

        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(413, 125, 130, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CharityManage/redcross log.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(280, 200, 240, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInvActionPerformed
        // TODO add your handling code here:
        ManageCharityInvJPanel manageCharityInvJPanel = new ManageCharityInvJPanel(userProcessContainer,enterprise,system);
        userProcessContainer.add("manageCharityInvJPanel", manageCharityInvJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngInvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngInv;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
