/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityManage;

import EcoSystem.EcoSystem;
import Person.Goods;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yanfei
 */
public class UpdateJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    Goods goods;
    
    
    public UpdateJPanel(JPanel userProcessContainer, EcoSystem business, Goods goods) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=business;
        this.goods=goods;
        
        labelName.setText(goods.getName());
        textNum.setText(String.valueOf(goods.getNum()));
        textCondition.setText(String.valueOf(goods.getCondition()));
        textEstimated.setText(String.valueOf(goods.getEstimatedPrice()));
        displayPic();
        
    }

    public void displayPic(){
            if(goods.getPicLink()!="empty"){
            ImageIcon icon = new ImageIcon(goods.getPicLink()); 


                 int conWidth = 230;
                 int conHeight = 162;
                  int imgWidth=icon.getIconWidth();  
                  int imgHeight=icon.getIconHeight();  
                 //int conWidth=PicLabel.getWidth();  
                  //int conHeight=PicLabel.getHeight();  
                  int reImgWidth;  
                  int reImgHeight;  
                  if(imgWidth/imgHeight>=conWidth/conHeight){  
                      if(imgWidth>conWidth){  
                          reImgWidth=conWidth;  
                          reImgHeight=imgHeight*reImgWidth/imgWidth;  
                      }else{  
                          reImgWidth=imgWidth;  
                          reImgHeight=imgHeight;  
                      }  
                  }else{  
                      if(imgWidth>conWidth){  
                          reImgHeight=conHeight;  
                          reImgWidth=imgWidth*reImgHeight/imgHeight;  
                      }else{  
                        reImgWidth=imgWidth;  
                          reImgHeight=imgHeight;  
                      }  
                  }

               icon=new ImageIcon(icon.getImage().getScaledInstance(reImgWidth, reImgHeight, Image.SCALE_DEFAULT)); 
               PicLabel.setIcon(icon);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNum = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textCondition = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PicLabel = new javax.swing.JLabel();
        PicBtn = new javax.swing.JButton();
        textEstimated = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Item Name");
        add(jLabel1);
        jLabel1.setBounds(396, 53, 68, 16);

        labelName.setText("jLabel2");
        add(labelName);
        labelName.setBounds(491, 53, 224, 16);

        jLabel3.setText("Quantity");
        add(jLabel3);
        jLabel3.setBounds(410, 96, 54, 16);
        add(textNum);
        textNum.setBounds(491, 91, 151, 26);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(750, 460, 88, 29);

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1);
        btnBack1.setBounds(90, 455, 75, 29);

        jLabel2.setText("Condition");
        add(jLabel2);
        jLabel2.setBounds(402, 142, 62, 26);
        add(textCondition);
        textCondition.setBounds(491, 142, 151, 26);

        jLabel4.setText("Estimated Price");
        add(jLabel4);
        jLabel4.setBounds(377, 199, 96, 16);
        add(PicLabel);
        PicLabel.setBounds(350, 270, 330, 200);

        PicBtn.setText("Picture");
        PicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PicBtnActionPerformed(evt);
            }
        });
        add(PicBtn);
        PicBtn.setBounds(740, 80, 87, 29);
        add(textEstimated);
        textEstimated.setBounds(491, 194, 151, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Admin/6783831-cute-backgrounds.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        boolean b = true;
        try{
            int number=Integer.valueOf(textNum.getText());
            double  condition = Double.valueOf(textCondition.getText());
            double estimatePrice = Double.valueOf(textEstimated.getText());
            
            goods.setNum(number);
            goods.setCondition(condition);
            goods.setEstimatedPrice(estimatePrice);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Please input valid numbers");
            b=false;
        }
        if(b){
            textCondition.setText("");
            textEstimated.setText("");
            textNum.setText("");
            JOptionPane.showMessageDialog(null, "Updated successfully!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void PicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PicBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setCurrentDirectory(new File("."));
        int result = chooser.showDialog(new JLabel(), "Select a Picture");
        if(result == JFileChooser.APPROVE_OPTION){
            //get image path
            String name = chooser.getSelectedFile().getPath();
            // Image image = new ImageIcon(name).getImage();
            ImageIcon icon = new ImageIcon(name);

            int imgWidth=icon.getIconWidth();
            int imgHeight=icon.getIconHeight();
            int conWidth=PicLabel.getWidth();
            int conHeight=PicLabel.getHeight();

            int reImgWidth;
            int reImgHeight;
            if(imgWidth/imgHeight>=conWidth/conHeight){
                if(imgWidth>conWidth){
                    reImgWidth=conWidth;
                    reImgHeight=imgHeight*reImgWidth/imgWidth;
                }else{
                    reImgWidth=imgWidth;
                    reImgHeight=imgHeight;
                }
            }else{
                if(imgWidth>conWidth){
                    reImgHeight=conHeight;
                    reImgWidth=imgWidth*reImgHeight/imgHeight;
                }else{
                    reImgWidth=imgWidth;
                    reImgHeight=imgHeight;
                }
            }

            icon=new ImageIcon(icon.getImage().getScaledInstance(reImgWidth, reImgHeight, Image.SCALE_DEFAULT));
            PicLabel.setIcon(icon);
            //save pic path
            goods.setPicLink(name);
        }
    }//GEN-LAST:event_PicBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PicBtn;
    private javax.swing.JLabel PicLabel;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField textCondition;
    private javax.swing.JTextField textEstimated;
    private javax.swing.JTextField textNum;
    // End of variables declaration//GEN-END:variables
}
